### ISSUE TITLE
MapBox - Houdini Console Stuff

### ISSUE THREAD

**Issue by deshudiosh** [sideeffects/GameDevelopmentToolset#101]
Hi.
Whenever change or refresh location in MapBox, houdini console spits out this message countless time:

`Qt Warn: WebGL: drawArrays: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering or is not 'texture complete'. Or the texture is Float or Half Float type with linear filtering while OES_float_linear or OES_half_float_linear extension is not enabled.`

Except for the error tool is working. 

I am on Win7x64, Hou 17.0.352.

**Comment by lkruel** [comment]
Yeah, that is a known issue. We'll look into a way into suppressing Qt warnings in a future Houdini version. But unfortunately that's a known issue. 

Thanks for reporting
