### ISSUE TITLE
'sop_physics_painter' crashes Houdini when simulating

### ISSUE THREAD

**Issue by Limbicnation** [sideeffects/GameDevelopmentToolset#102]
'sop_physics_painter' crashes Houdini 17.0.352 when simulating

**Comment by Limbicnation** [comment]
Log file:
`Crash report from ##### Houdini FX Version 17.0.352 [windows-x86_64-cl19.15]
Uptime 302 seconds
Wed Nov 21 19:43:21 2018
Caught signal 11

Traceback from 24516 ThreadId=0x000032ec
CURRENT THREAD 13036
+0x3bc6c0e4 C:\PROGRA~1\SIDEEF~1\HOUDIN~1.352\houdini\dso\SIM_SolverBullet.dll
+0x3bc97ba3 C:\PROGRA~1\SIDEEF~1\HOUDIN~1.352\houdini\dso\SIM_SolverBullet.dll
+0x3bc9c13e C:\PROGRA~1\SIDEEF~1\HOUDIN~1.352\houdini\dso\SIM_SolverBullet.dll
+0x3bcb4cbe C:\PROGRA~1\SIDEEF~1\HOUDIN~1.352\houdini\dso\SIM_SolverBullet.dll
+0x3bcd0717 [newSopOperator] C:\PROGRA~1\SIDEEF~1\HOUDIN~1.352\houdini\dso\SIM_SolverBullet.dll
+0x0e77c14a [SIM_Solver::solveObjects] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libSIM.dll
+0x0e6298c3 [SIM_Engine::doSimulationStepForMetaObject] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libSIM.dll
+0x0e628813 [SIM_Engine::doSimulationStep] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libSIM.dll
+0x0e62fcde [SIM_Engine::setSimulationTime] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libSIM.dll
+0x1852d412 [DOP_Parent::setDOPTimeSubclass] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libDOP.dll
+0x1c0b4346 [SOP_Dopnet::setDOPTimeSubclass] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libSOPZ.dll
+0x1852d1f9 [DOP_Parent::setDOPTime] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libDOP.dll
+0x1c0b221a [SOP_Dopnet::cookMySop] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libSOPZ.dll
+0x0cf91560 [SOP_Node::cookMe] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libSOP.dll
+0x16db940b [OP_OTLOptions::operator!=] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libOP.dll
+0x16dc54bf [OP_Node::cook] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libOP.dll
+0x16de39eb [OP_Node::internalCookInput] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libOP.dll
+0x16de828a [OP_Node::lockInput] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libOP.dll
+0x0cf98680 [SOP_Node::lockInput] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libSOP.dll
+0x16cb4b11 [OP_AutoLockInputs::lockInput] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libOP.dll
+0x0cf8faf2 [SOP_Node::cookGuideList] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libSOP.dll
+0x0cafda0e [SOP_NodeVerb::cookInputs] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libSOP.dll
+0x0cf9187f [SOP_Node::cookMyselfAsVerb] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libSOP.dll
+0x0cf91560 [SOP_Node::cookMe] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libSOP.dll
+0x16db940b [OP_OTLOptions::operator!=] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libOP.dll
+0x16dc54bf [OP_Node::cook] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libOP.dll
+0x0cf877b3 [SOP_Node::AttribTupleIndexArg::operator int] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libSOP.dll
+0x0cf94b11 [SOP_Node::getCookedGeoHandle] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libSOP.dll
+0x0d193411 [SOP_SubNet::cookMySop] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libSOP.dll
+0x0cf91560 [SOP_Node::cookMe] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libSOP.dll
+0x16db940b [OP_OTLOptions::operator!=] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libOP.dll
+0x16dc54bf [OP_Node::cook] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libOP.dll
+0x16de39eb [OP_Node::internalCookInput] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libOP.dll
+0x16de828a [OP_Node::lockInput] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libOP.dll
+0x0cf98680 [SOP_Node::lockInput] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libSOP.dll
+0x0d1b1b85 [SOP_Switch::cookMySop] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libSOP.dll
+0x0cf91560 [SOP_Node::cookMe] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libSOP.dll
+0x16db940b [OP_OTLOptions::operator!=] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libOP.dll
+0x16dc54bf [OP_Node::cook] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libOP.dll
+0x16de39eb [OP_Node::internalCookInput] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libOP.dll
+0x16de828a [OP_Node::lockInput] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libOP.dll
+0x0cf98680 [SOP_Node::lockInput] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libSOP.dll
+0x16cb4b11 [OP_AutoLockInputs::lockInput] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libOP.dll
+0x0cf8faf2 [SOP_Node::cookGuideList] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libSOP.dll
+0x0cafda0e [SOP_NodeVerb::cookInputs] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libSOP.dll
+0x0cf9187f [SOP_Node::cookMyselfAsVerb] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libSOP.dll
+0x0cf91560 [SOP_Node::cookMe] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libSOP.dll
+0x16db940b [OP_OTLOptions::operator!=] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libOP.dll
+0x16dc54bf [OP_Node::cook] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libOP.dll
+0x16de39eb [OP_Node::internalCookInput] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libOP.dll
+0x16de828a [OP_Node::lockInput] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libOP.dll
+0x0cf98680 [SOP_Node::lockInput] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libSOP.dll
+0x16cb4b11 [OP_AutoLockInputs::lockInput] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libOP.dll
+0x0cf8faf2 [SOP_Node::cookGuideList] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libSOP.dll
+0x0cafda0e [SOP_NodeVerb::cookInputs] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libSOP.dll
+0x0cf9187f [SOP_Node::cookMyselfAsVerb] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libSOP.dll
+0x0cf91560 [SOP_Node::cookMe] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libSOP.dll
+0x16db940b [OP_OTLOptions::operator!=] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libOP.dll
+0x16dc54bf [OP_Node::cook] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libOP.dll
+0x16de39eb [OP_Node::internalCookInput] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libOP.dll
+0x16de828a [OP_Node::lockInput] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libOP.dll
+0x0cf98680 [SOP_Node::lockInput] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libSOP.dll
+0x16cb4b11 [OP_AutoLockInputs::lockInput] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libOP.dll
+0x0cf8faf2 [SOP_Node::cookGuideList] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libSOP.dll
+0x0cafda0e [SOP_NodeVerb::cookInputs] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libSOP.dll
+0x0cf9187f [SOP_Node::cookMyselfAsVerb] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libSOP.dll
+0x0cf91560 [SOP_Node::cookMe] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libSOP.dll
+0x16db940b [OP_OTLOptions::operator!=] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libOP.dll
+0x16dc54bf [OP_Node::cook] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libOP.dll
+0x0cf877b3 [SOP_Node::AttribTupleIndexArg::operator int] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libSOP.dll
+0x0cf94b11 [SOP_Node::getCookedGeoHandle] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libSOP.dll
+0x0d193411 [SOP_SubNet::cookMySop] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libSOP.dll
+0x0cf91560 [SOP_Node::cookMe] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libSOP.dll
+0x16db940b [OP_OTLOptions::operator!=] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libOP.dll
+0x16dc54bf [OP_Node::cook] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libOP.dll
+0x16de39eb [OP_Node::internalCookInput] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libOP.dll
+0x16de828a [OP_Node::lockInput] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libOP.dll
+0x0cf98680 [SOP_Node::lockInput] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libSOP.dll
+0x0cfbd23d [SOP_Output::cookMySop] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libSOP.dll
+0x0cf91560 [SOP_Node::cookMe] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libSOP.dll
+0x16db940b [OP_OTLOptions::operator!=] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libOP.dll
+0x16dc54bf [OP_Node::cook] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libOP.dll
+0x0cf877b3 [SOP_Node::AttribTupleIndexArg::operator int] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libSOP.dll
+0x0cf94b11 [SOP_Node::getCookedGeoHandle] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libSOP.dll
+0x0d193411 [SOP_SubNet::cookMySop] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libSOP.dll
+0x0cf91560 [SOP_Node::cookMe] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libSOP.dll
+0x16db940b [OP_OTLOptions::operator!=] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libOP.dll
+0x16dc54bf [OP_Node::cook] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libOP.dll
+0x0cf877b3 [SOP_Node::AttribTupleIndexArg::operator int] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libSOP.dll
+0x0cf94b11 [SOP_Node::getCookedGeoHandle] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libSOP.dll
+0x074b077c [OBJ_Node::getDisplayGeometryHandle] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libOBJ.dll
+0x0663d8dd [JEDI_View::opuiUpdateNodeInfo] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libJEDI.dll
+0x181b4dd2 [OH_OpHandler::opuiUpdateData] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libOH.dll
+0x068127c8 [OP3D_View::doUpdate] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libOP3D.dll
+0x1b78ad88 [tbb::interface7::internal::task_arena_base::internal_execute] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\tbb.dll
+0x38421175 [TBBPROXY_TaskArenaExecute] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libTBBPROXY.dll
+0x0663cadb [JEDI_View::opuiUpdateData] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libJEDI.dll
+0x181b51b8 [OH_OpHandler::trigger] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libOH.dll
+0x057d4724 [UI_Queue::processNextEvent] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libUI.dll
+0x057d24e9 [UI_Queue::drain] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libUI.dll
+0x057d2878 [UI_Queue::eventLoop] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libUI.dll
+0x0556c7f0 [AP_Interface::loadWindowGeometry] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libSI.dll
+0x0556d25d [myWinMain] C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\libSI.dll
+0x40001b9a C:\Program Files\Side Effects Software\Houdini 17.0.352\bin\houdini.exe
+0x0ee07e94 [BaseThreadInitThunk] C:\WINDOWS\System32\KERNEL32.DLL
+0x0ef47ad1 [RtlUserThreadStart] C:\WINDOWS\SYSTEM32\ntdll.dll

`

**Comment by Limbicnation** [comment]
The issue was resolved in version 17.0.404

**Comment by Ambrosiussen** [comment]
Hi,

This was caused due to a problem with the bullet solver in Houdini itself.
PhysicsPainter now supports Heightfields as input, but the solver did not like that until a recent build.

Updating is the correct solution! :)

Paul
