### ISSUE TITLE
rop_games_baker Linux temp environment variable

### ISSUE THREAD

**Issue by brunokindt** [sideeffects/GameDevelopmentToolset#103]
The pre_bake0 node inside rop_games_baker.hda displays the following error
```
Python error: Traceback (most recent call last):
File "", line 1, in 
File "opdef:/gamedev::Driver/rop_games_baker?PythonModule", line 50, in pre_bake
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

The cause seems to be a none existing environment variable inside the PythonModule script.

`temp_path = hou.getenv("temp")`

Changing the lines to `temp_path = hou.getenv("HOUDINI_TEMP_DIR")`
or adding a temp variable in 'Aliases and Variables' resolves the issue. 

details:

GameDevelopmentToolset Development branch ( commit 09bbc5f7eca2842b4cba19fbc97f732d2744ed36  of Fri Nov 23 14:14:02 2018 -0800 ) 
Houdini FX Version 17.0.352
Operating System: Fedora release 28 (Twenty Eight)

**Comment by Ambrosiussen** [comment]
Hi,

Thanks for reporting. This has been fixed in release 1.91 and newer.

Paul
