### ISSUE TITLE
3D Noise for SOP Branches

### ISSUE THREAD

**Issue by electroheadfx** [sideeffects/GameDevelopmentToolset#110]
A 2D noise is used in branch SOP, why not use the deform on the 3D space ? Branches should not grown on all axis ?

**Comment by lkruel** [comment]
I believe a 3d noise is being used currently. But I'm not super happy with it myself quite yet. What effect are you looking for that you feel you cant hit? Is it more variation per branch?

**Comment by electroheadfx** [comment]
ok, take a look at capture : 
![unified_noise](https://user-images.githubusercontent.com/1211149/53815084-3a0fc380-3f61-11e9-813a-e376ef797709.jpg)

![testaanoise](https://user-images.githubusercontent.com/1211149/53815092-3e3be100-3f61-11e9-9e8a-1ed1f2b4cb61.jpg)

**Comment by electroheadfx** [comment]
the unified doesn't work in 3D on wire I dont understand so your wire deform only on 2 axis. Unified noise is better for volume/vdb creation, but its too slow just for wire deform. I will use just a fast simply noise.

**Comment by lkruel** [comment]
Ah thanks for that! 

I've modified the noise to use the one shown

**Comment by electroheadfx** [comment]
Why use this displacement noise instead of a Simple Add node ?? Displacement node create a 2D noise on the line, it deform only on 2D axis. It need to setup too the noise to 3D.

![default](https://user-images.githubusercontent.com/1211149/53864460-d206bf00-3fec-11e9-8694-1c0f47d4bfcf.jpg)

![setup](https://user-images.githubusercontent.com/1211149/53864468-d632dc80-3fec-11e9-9301-b8a4cbe613e1.jpg)
