### ISSUE TITLE
Gravity for SOP Branches

### ISSUE THREAD

**Issue by electroheadfx** [sideeffects/GameDevelopmentToolset#111]
Hey, should not add a gravity feature to this great SOP Branches ??

**Comment by lkruel** [comment]
There is a vertical offset that should tilt the branches and also a curl parameter for bending them. What would you expect the gravity parameter to do? Similar to the curl?

**Comment by electroheadfx** [comment]
ah ok I see with a curl to -0.002 and a vertical offset between 0.5 and 1, it does something similar to gravity. Maybe a slider combiner called gravity to keep the thing simple ? its up to you :)
thanks

**Comment by lkruel** [comment]
Yeah, the thought was to keep them separate so you might have a tree that has branches that go straight up, or leaves that hang down but curl up. I'll keep an ear out for feedback, a gravity slider does seem more intuitive but I think having the 2 controls might be more flexible
