### ISSUE TITLE
Flow map visualize - respect flow speed

### ISSUE THREAD

**Issue by huwb** [sideeffects/GameDevelopmentToolset#112]
Hello, great work with the game dev toolset.

We're generating flow maps from a simulation and we need the speed of the flow respected when visualizing the flow. We're using a flowmap-to-colour followed by a flowmap-visualize. The former normalizes the flow vector, and the latter unpacks the flow from 0-1 values and then uses a set Speed.

Locally i've changed these nodes in my scene to not do this normalize, and not do any unpacking (take RG values as is), and this way we can get the correct flow visualised. This unblocks us but I wanted to send this through as feedback in case its useful, if not you can close this.

Thanks
Huw

**Comment by lkruel** [comment]
Thanks! 

I've removed the normalization from the ToColor node, which should let you have the speed scale built into the vector. The unpacking is still needed so we go from -1 - 1 instead of 0 - 1, otherwise you can't have negative movement, but the normalization was definitely the problem there.

**Comment by huwb** [comment]
Nice one! 👍
