### ISSUE TITLE
Zbrush 2019: GoZ Houdini 17.0.549 -> Unable to read from file.

### ISSUE THREAD

**Issue by Limbicnation** [sideeffects/GameDevelopmentToolset#115]
Unable to read file: "C:\Users\Public\Pixologic\GoZProjects\Default"

**Comment by Limbicnation** [comment]
I still have the same Problem in 17.5.173 with the GameDevelopmentToolset branch -> development -> "Unable to read file.."

**Comment by mifth** [comment]
I had a problem too.
I installed H17.5.200. Then I updated GDTools to 1.136 and reloaded Houdini. All works fine with this setup.

**Comment by lkruel** [comment]
We solved this on discord, so closing this out. His houdini.env was reading an older version of the toolset.
