### ISSUE TITLE
Branch17.0 DSO Error

### ISSUE THREAD

**Issue by bonsak** [sideeffects/GameDevelopmentToolset#119]
Loading Branch17.0 in H17.0.506 results in error dialog when starting H:
"Houdini DSO Error
{126} Couldn`t load ......./dso/RealityCapture_SOP.dll
This is probably because this file was intended for use with a different version of Houdini"

**Comment by lkruel** [comment]
I can't repro this, are you sure that you didn't have Houdini open when you changed branches? That could've caused the dll to be loaded and not writable

**Comment by bonsak** [comment]
Pretty sure. I can try again tomorrow.

**Comment by bonsak** [comment]
Strange. Bypassed GIT and dl`ed the zip file for 17 branch manually, but i still get the same error on startup.

**Comment by bonsak** [comment]
Seems its only happening on one machine. Ill investigate further.
