### ISSUE TITLE
Mapbox doesn't work for Asia

### ISSUE THREAD

**Issue by prrrszalony** [sideeffects/GameDevelopmentToolset#121]
Hello,

Mapbox doesn't work for Asia. It works for every other continent. In Unity Mapbox works just fine.

I tested this on Houdini 17.5.173 and 17.5.229 with various Toolset versions from 1.31 to1.53.

![obraz](https://user-images.githubusercontent.com/12631410/56851328-fa84a880-690d-11e9-9d01-651cc395d6cd.png)

file with random places https://www.dropbox.com/s/m8szbs0h8vj7aul/del_mapbox.hiplc?dl=0

**Comment by lkruel** [comment]
It was having a hard time with negative coordinates, I've updated the tool to work properly

**Comment by prrrszalony** [comment]
Hi, 
Thanks for quick fix!
Unfortunately there is small bug after that. There is big crease in the middle.

![obraz](https://user-images.githubusercontent.com/12631410/57060918-66bf2d80-6cbb-11e9-9536-b70d18f3d0d8.png)

Thank you!
