### ISSUE TITLE
Uninstall doesn't seem to remove subdirectory and contents (H17.5.232)

### ISSUE THREAD

**Issue by johnnyquest** [sideeffects/GameDevelopmentToolset#122]
The "update toolset" shelf tool's python script, around line 311:

`removedir = os.path.join(HOU_TEMP_PATH, version)`

I think it's supposed to be

`removedir = os.path.join(HOU_TEMP_PATH, APP_VERSION, version)`

At least this is how it looks like in Houdini 17.5.232 (I'm not sure if this shelf button gets updated when the update is loaded, so I don't know if I was looking at the latest version)

**Comment by lkruel** [comment]
Thanks for this report. It's actually distributed with Houdini proper, but we've made the changes and it should be on a future build soon
