### ISSUE TITLE
What is the way to export Instances?

### ISSUE THREAD

**Issue by Schizo** [sideeffects/GameDevelopmentToolset#124]
I've just realized that the `RBD to FBX` Export doesn't generate instances, which is fine as most RBD's don't contain instances but for large scale stuff or packed prim simulation's that would be great. Would like to here what you guys thought about this. Currently I'm using the python api to write out the position's to read it back in Unreal.

**Comment by lkruel** [comment]
Yeah it would probably need to be something external like what you have setup, since I don't believe you can export separate actors with FBX
