### ISSUE TITLE
Failed to load license for Reality Capture

### ISSUE THREAD

**Issue by Limbicnation** [sideeffects/GameDevelopmentToolset#127]
I can’t get RC to work in Houdini, after I’ve made the activation in browser. 
![RC](https://user-images.githubusercontent.com/6284675/57815420-a126d100-7777-11e9-9889-a56e48c3b08b.JPG)

**Comment by Limbicnation** [comment]
Both tried Production and development build.

**Comment by lkruel** [comment]
Works over here. Do you have a license file in your $HOME directory?

**Comment by Limbicnation** [comment]
Unfortunately I don't see a license file in my $HOME directory.

**Comment by lkruel** [comment]
Solved this offline with the user. Ended up needing to run Houdini as an Admin because it was trying to write the license file likely somewhere in program files
