### ISSUE TITLE
Rop Vector node missing

### ISSUE THREAD

**Issue by Psynema** [sideeffects/GameDevelopmentToolset#13]
https://www.sidefx.com/tutorials/exporting-vector-fields-to-ue4/

 Anyone know why my ROP_vector_field is missing?  I have 16.0.632 (latest) and also was missing in 0.6.25 version.

I have installed the game development toolset folder in my Documents/houdini16.0 folder and copied the path to the game development folder in the env file.  Am I missing something?  It works for this guy above?

**Comment by lkruel** [comment]
Hey Psynema, sorry for the late reply. Can you download the Development branch if you're still having issues?
