### ISSUE TITLE
Vertex animation textures BBOX values are always 0

### ISSUE THREAD

**Issue by wavebit** [sideeffects/GameDevelopmentToolset#130]
I downloaded a [hip](https://www.sidefx.com/forum/attachment/4566fea96251eedf34fd5b4bf177439fd0b4ed67/) made by @mikelyndon-sesi, then I add a vertex animation textures node to do a quick test.

In houdini 17.5.264, Game Development Toolset 1.165, the BBOX MAX 1 and BBOX MIN 1 are always 0, even I put the ground plane lower than 0.
![cap17 5 264](https://user-images.githubusercontent.com/11334491/58253304-b369c600-7d9a-11e9-8b04-a55ad02cb44d.PNG)

Below from houdini 17.0.506, Game Development Toolset 1.165, 
![cap17 0 506](https://user-images.githubusercontent.com/11334491/58253637-794cf400-7d9b-11e9-8400-cad38ef73b19.PNG)

**Comment by mikelyndon-sesi** [comment]
This was due to the script that sets BBOX MIN and MAX calculating the values incorrectly. This has been fixed.

**Comment by wavebit** [comment]
I have tested the v1.167. If export dopimportSOP(fetch geometry from DOP network),  the BBOX is cut to 1000/-1000.
![cap3](https://user-images.githubusercontent.com/11334491/58391504-bf8aa780-8068-11e9-9e0b-c5e070c54936.PNG)

Direct export DOPNetwrork node, the BBOX seems are right, but all fractures are off in UE4, and the playback is very strange.

![cap1](https://user-images.githubusercontent.com/11334491/58391650-5bb4ae80-8069-11e9-9acf-0353bf23ec03.png)
![cap](https://user-images.githubusercontent.com/11334491/58391657-62432600-8069-11e9-8274-b5ff03afa67b.PNG)

![rbd_vat_1](https://user-images.githubusercontent.com/11334491/58392528-f9f64380-806c-11e9-9316-d54c5518098d.gif)
![rbd_vat_2](https://user-images.githubusercontent.com/11334491/58392533-fcf13400-806c-11e9-9064-3e5281d564ba.gif)

**Comment by mikelyndon-sesi** [comment]
Please post these issues on the sidefx forum in the realtime section.
https://www.sidefx.com/forum/68/
