### ISSUE TITLE
There is a bug in "Destruction Cleanup" node

### ISSUE THREAD

**Issue by sevelee** [sideeffects/GameDevelopmentToolset#132]
This node use the "w" property of point to identify whether the point is a moving chunk or not.
But sometimes, like in my case, I freeze all the chunks in the end of sim so that the w is all ZERO in the end.
I suggest to use "orient" or make this a option.

Was:
![image](https://user-images.githubusercontent.com/8036235/58313311-d9957180-7e3f-11e9-94eb-e832b1953506.png)

Should be:
![image](https://user-images.githubusercontent.com/8036235/58313360-f29e2280-7e3f-11e9-9dae-551c497cf04a.png)

**Comment by Ambrosiussen** [comment]
Hi!

Thank you for the recommendation! I will add this as an option :)

Paul
