### ISSUE TITLE
Instant meshes dialog doens't appear in RHEL 7.6

### ISSUE THREAD

**Issue by queglay** [sideeffects/GameDevelopmentToolset#140]
Hello, I'm wondering if there are any tricks needed to see the dialog in linux for instant meshes.  in the sop, disabling "hide instant meshes dialog" doesn't work.

**Comment by Ambrosiussen** [comment]
Hi, 

Did you download the executables for Linux? (and point to them in the correct parameter)
If that did not work, please submit this issue to support@sidefx.com, since we are moving support to there instead of here.

Paul
