### ISSUE TITLE
Simple Baker - Unchecking "Vertex Color" leads to an error while rendering.

### ISSUE THREAD

**Issue by ya00x** [sideeffects/GameDevelopmentToolset#141]
![simpleBakerError](https://user-images.githubusercontent.com/51844005/60316570-153cc300-9939-11e9-9bfc-96b1f922a1ff.gif)

I'm using Houdini Indie version 17.5.293
GameDevelopmentToolset version 1.173

**Comment by mikelyndon-sesi** [comment]
Thanks for pointing this out. I'm submitting a fix later today that should resolve the issue. You should see the update in tomorrow's daily build.
