### ISSUE TITLE
remove .OPfallbacks during a release?

### ISSUE THREAD

**Issue by pbowmar** [sideeffects/GameDevelopmentToolset#158]
Hi,

I notice that many/most of the OTLs have .OPfallbacks that point to Windows paths, plus are quite specific to whatever user is creating the OTL.

I'd suggest that as part of a release you strip those out, to help avoid that causing problems outside the environment they were created in.

In theory they're fairly harmless but it would be nice if this wasn't too hard to implement.

I just do (in Tcsh):

```
foreach i (`find . -iname ".OPfallback"`)
rm $i
end
```

so I can do it myself of course :)

**Comment by Ambrosiussen** [comment]
Hi,

Thank you for that tip! I have removed them from the releases, and added them to the .gitignore file to prevent them from coming back again in the future :) 

Paul
