### ISSUE TITLE
Renaming repo to Labs or similar

### ISSUE THREAD

**Issue by manuelkoester** [sideeffects/GameDevelopmentToolset#177]
Hey guys,

since you are now under the Labs banner, could we also update the name of this repo/create a new one nd retire this/..?

Thanks!

**Comment by lkruel** [comment]
There already is a https://github.com/sideeffects/SideFXLabs. We're moving development over there but will keep this open for people that haven't moved over to 18.0 yet.

**Comment by manuelkoester** [comment]
Perfect Luiz!
