### ISSUE TITLE
How do you automate?

### ISSUE THREAD

**Issue by laurentopia** [sideeffects/GameDevelopmentToolset#181]
Wonderful set of tools, I was impressed by auto UV.
Now I'd like to have houdini sit in the background and detect new fbx that I output from Medium and then, in the background auto decimate that, auto uv that export the mesh in the same folder then launch the bake while using less than the total number of cores, so I can keep sculpting something else.
how do I do that?

**Comment by lkruel** [comment]
You'll need to write a filewatcher to trigger some python script. You can take a look at https://srinikom.github.io/pyside-docs/PySide/QtCore/QFileSystemWatcher.html for some ideas.

**Comment by laurentopia** [comment]
thank you for the direction
