### ISSUE TITLE
rop_games_baker node ignores resolution

### ISSUE THREAD

**Issue by trojanfoe** [sideeffects/GameDevelopmentToolset#19]
(In the Development branch at the time of writing).

The Games Baker node ignores the resolution settings and always bakes at 256x256.

**Comment by trojanfoe** [comment]
The resolution parms just aren't hooked-up in the `baketexture` node:

![image](https://user-images.githubusercontent.com/312617/28129503-73116f18-672b-11e7-8dbd-3e2239c592ec.png)

**Comment by lkruel** [comment]
Thanks for reporting this! It has been fixed in the Development branch which will be merged into 16.0 today
