### ISSUE TITLE
OSM importer python errors

### ISSUE THREAD

**Issue by subTropic** [sideeffects/GameDevelopmentToolset#25]
I cant seem to get the OSM importer to work on Linux, the python node fails with: 

File"", line 203, in
File"", line 129, in build
AttributeError:'Geometry'object has no attribute 'createPoints'

using h16

works fine on osx

**Comment by lkruel** [comment]
That's odd, are you using the same Houdini version on both OS? What you're reporting is a difference in the python API which seems really strange

**Comment by subTropic** [comment]
linux version is 16.0.5.39
osx version is 16.0.633
Just tried on linux with 16.0.633 and is now working as expected. 
Thank you!
