### ISSUE TITLE
Missing RBD textures ?

### ISSUE THREAD

**Issue by stef-levesque** [sideeffects/GameDevelopmentToolset#27]
I'm looking for the simple_rbd_pos and simple_rbd_rot textures, as seen in the [Unity tutorial](https://www.sidefx.com/tutorials/unity-shaders-for-vertex-animation-export-tools/) Rigid Bodies @ 6:20

I couldn't found them in the [vertex_animation_examples.unitypackage](/sideeffects/GameDevelopmentToolset/blob/Houdini16.0/unity/vertex_animation_examples.unitypackage)

**Comment by Ambrosiussen** [comment]
Hi,

These textures have been made by the developer, and would be replaced with your own. (Generated using the tool)

Paul

**Comment by stef-levesque** [comment]
Thanks, in 6 months, we got it figured out :)

In the meanwhile, we got integrated in the Frostbite Engine and it's working (almost) flawlessly !
