### ISSUE TITLE
No FBX on render

### ISSUE THREAD

**Issue by jBachalo** [sideeffects/GameDevelopmentToolset#30]
Returning to same project I am unable to create fbx. Using dev branch (Vertex Animation Textures Beta).
On render I generate position and normal maps but no fbx. No error is generated,
Obvious cause would be if running Apprentice but definitely is Indie 16.0.705

Can you suggest troubleshooting steps?

**Comment by shalivan** [comment]
Hi. I have simillar problem. Time to time I have no position map in baked folder, but in my case it's random, and when I changed render frames range it gone. I'm still trying to find any  dependences when it occurre.

**Comment by Ambrosiussen** [comment]
Marking as closed, since no similar bugs have been reported after several updates.
