### ISSUE TITLE
Games Baker ROP Not rendering textures

### ISSUE THREAD

**Issue by SooiCC** [sideeffects/GameDevelopmentToolset#35]
I'm using the Dev branch, Houdini Apprentice 16.0.705 and following this tutorial by Luiz Kruel: https://www.sidefx.com/tutorials/games-baker-rop/

Unwrapping works great but when I try to render with the Games Baker ROP I get an error.

The Game Baker node gives me this error: 

`Error rendering child: /out/rop_games_baker1/baketexture `

and when I open it up, the baketexture node gives me this error: 

```
Error 
Command Exit Code: 1

[14:42:57] mantra: Mantra tile imager open failure: Tiled Image File: 0 file []
File: C:/Users/Administrator/render\\LOW_tmp.exr
File: C:/Users/Administrator/render\\LOW_tmp.exr
File: C:/Users/Administrator/render\\LOW_tmp.exr
File: C:/Users/Administrator/render\\LOW_tmp.exr
[14:42:57] mantra: Could not open imager
[14:42:57] mantra: UV rendering failed for object /out/rop_games_baker1/objnet/low 
```
I tried running Houdini as administrator as someone suggested somewhere else but that didn't change anything.

I'm very new to Houdini so I might be missing something.

![issue01](https://user-images.githubusercontent.com/1348538/31078208-7ff8ec06-a781-11e7-8dab-542914a334e1.JPG)
![issue02](https://user-images.githubusercontent.com/1348538/31078207-7ff8ca8c-a781-11e7-95a7-be05240d33c3.JPG)

**Comment by aboubakrvfx** [comment]
i think that you have to save the scene first before you render

**Comment by SooiCC** [comment]
@aboubakrvfx 
Not sure if you mean just saving the project because I have done that and just getting the same results.

Sorry if this is basic stuff, I'm very new to the software.

**Comment by aboubakrvfx** [comment]
change the location try in document or even in another hard drive

**Comment by SooiCC** [comment]
@aboubakrvfx Now I get an extra error in the pre_bake0 node.

![issue04](https://user-images.githubusercontent.com/1348538/31080344-b866f0a4-a788-11e7-8c3f-f711f91de0b0.JPG)
![issue03](https://user-images.githubusercontent.com/1348538/31080345-b889c1c4-a788-11e7-965b-5423734c3f36.JPG)

**Comment by aboubakrvfx** [comment]
@sooi11 
![text_](https://user-images.githubusercontent.com/28587686/31080626-273fc4ea-a781-11e7-980f-5ac5e5af6488.jpg)
try change the "\" by /

**Comment by aboubakrvfx** [comment]
also try to follow those steps, https://vimeo.com/236097388#t=405s

**Comment by SooiCC** [comment]
I followed the tutorial step by step with the exact same model and I'm getting the same errors in both 'baketexture' and 'pre_bake0'.

**Comment by aboubakrvfx** [comment]
@sooi11 this is weird , cuz i have this problem when i don't save the scene , all what i do is to save it in a folder . .... wait a sec .....i think i'm blind XD ... dude try to re download the otls files and re install them , you have a huge problem here XD .... here how it should look in the rop_games_baker [https://puu.sh/xOeaJ/05c6554bce.png](url)

**Comment by SeriousElliot** [comment]
I'm having the exact same error. I'm running the apprentice version - is it possible that the resolution limits on the renderer are causing issues with the bake process?
I've tried setting the output resolution to as low as 128x128 and that hasn't solved it.

@aboubakrvfx the image attachment you uploaded above isn't loading so I'm not clear if I have the same installation issues you are alluding to.

Thanks in advance for any help...

**Comment by aboubakrvfx** [comment]
sorry here how it should be connected , just try to re-download the otls as i said https://github.com/sideeffects/GameDevelopmentToolset  , it should be fixed 
![2017-10-02_15-41-29](https://user-images.githubusercontent.com/28587686/31113333-b76d8144-a810-11e7-9ab2-fc9ceb26be7f.png)

**Comment by SooiCC** [comment]
Oh ok, just found out that the Apprentice version has a resolution limit. 
Anything up to 512x512 works fine.

So I guess this is solved.

**Comment by SeriousElliot** [comment]
Updating the tools (plus lower res) fixed things for me as well.
Thanks guys.

**Comment by simonreeves** [comment]
using 17.5 and have tried cloning the repo as well as using a release and I am similar issues, noticed that inside the OTL I do not have that switch, nodes are disabled, seems odd! Using, core, tried FX no difference
![image](https://user-images.githubusercontent.com/12150445/58194095-821ac880-7cbc-11e9-9942-a75724a40ce0.png)
