### ISSUE TITLE
Latest Vertex Animation Textures Beta crashes on custom frame range Export

### ISSUE THREAD

**Issue by GabrielCharest** [sideeffects/GameDevelopmentToolset#39]
I found a possible bug using the Latest Vertex Animation Texture Beta (from the development branch) that is related to the fact I'm using a Make Loop tool and starting my animation to a frame not equal to 0.

As described [here](http://www.sidefx.com/docs/houdini/cloth/flag), I simply created a tube, then a grid that I attached together and added some wind. Cached the results, and then using the Make Loop I choose frame 100 as start frame and 450 as End Frame. I adjusted my global animation options accordingly.

The I create a Vertex Animation Textures Beta and select my Grid/Output node and unchecked the Pack Normal into Alpha option.

The Render Normal node will generate some errors. Error rendering Child: /out/vertexanimationtexturesbeta1/RENDER_NORMAL.

In the subnode RENDER_NORMAL, the error says Failed to Retreive Pixel Information. 

Please let me know if you need more information

**Comment by Ambrosiussen** [comment]
Hi,

This bug has _finally_ been fixed, and should be live in the 1.9 Development release of the toolset.

Paul
