### ISSUE TITLE
Unity - Impostor Alpha Blended shader errror in Unity 2017.2.of3

### ISSUE THREAD

**Issue by Limbicnation** [sideeffects/GameDevelopmentToolset#44]
![impostoralphablended](https://user-images.githubusercontent.com/6284675/32359268-1effd902-c04d-11e7-9699-0a6dd6799c76.jpg)

//Shader error in 'sidefx/Impostor Alpha Blended': Vertex program 'vert': unknown input semantics TEXOORD/1
 (on d3d11)

**Comment by tractopoutre** [comment]
typo line 64 of the shader, replace `TEXOORD1` by `TEXCOORD1`

**Comment by Limbicnation** [comment]
Thanks, that was a quick fix. I should have spotted that too!
