### ISSUE TITLE
Vertex animation is missing from shelf with auto update 16.5.

### ISSUE THREAD

**Issue by KenzieMac130** [sideeffects/GameDevelopmentToolset#48]
Not sure if this is only an issue with the auto-updater but the amazing vertex animation cache feature appears to have been removed or at least unavailable without downloading it manually.

**Comment by lkruel** [comment]
Hey there, 

I've added it back to the shelf in the 16.5 branch which will get pushed into Development tomorrow. But do know that you were always able to just manually instance the tool through the TAB menu
