### ISSUE TITLE
Instant Meshes - Meshes Intersecting

### ISSUE THREAD

**Issue by BellaCoola** [sideeffects/GameDevelopmentToolset#50]
Hello,

I had the same issue as user 099440a80f774063a1e115922 at this site: https://www.sidefx.com/tutorials/houdini-game-dev-tools-instant-meshes-bridge/

After running instant meshes OTL I got intersections on the result geometry
After some trial and error with instant meshes cmdline options I figured out that it can be fixed by using -D (dominant) flag

in context of this OTL I added:
cmd.append("-D")
before this line:
cmd.append("-f")

I am not sure if this hardware specific issue, but I hope that it could be helpful for some other users :)

Have a nice day

**Comment by Limbicnation** [comment]
Hi Thank you for then info regarding this particular issue.
However I'm getting the following error, after adding the above command

Error | Python error: SyntaxError: ('invalid syntax', ('', 15, 12, 'cmd.append(\n'))
-- | --

**Comment by BellaCoola** [comment]
thats strange in my case it works without flaw, do you use newest version of instant meshes?

**Comment by Limbicnation** [comment]
Cool thanks! I forgot to add the slashes: `cmd.append(\"-D\")`

**Comment by Limbicnation** [comment]
It's working now.

**Comment by lkruel** [comment]
I've added these changes to the 16.5 branch. I'm hoping to merge it back into Development first thing Monday morning. I've also exposed the crease angle command line argument 

Thanks for the suggestions!

https://vimeo.com/244246770/929a20e59a

**Comment by Limbicnation** [comment]
Thank you for this update Luiz!
