### ISSUE TITLE
"Update Toolset" button error

### ISSUE THREAD

**Issue by gitToad** [sideeffects/GameDevelopmentToolset#52]
Houdini Indie 16.5
GameDevToolset 16.6 branch

Pressing "Update Toolset" button on Game shelf shows error dialog:
_"NoneType" object has no attribute "endswith"_

Show Details on that dialog produces:
_Traceback (most recent call last):
  File "update_toolset", line 18, in <module>
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.py", line 70, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'_

**Comment by lkruel** [comment]
Thanks for reporting this. We are aware of issues with the autoupdater in Linux and Mac, and are working on the best solution for it

**Comment by lkruel** [comment]
This has been fixed on the Development branch :D Friday's Houdini Daily has also fixed another issue with HTTPS connections for downloads. This change will hopefully be in a daily build in the near future
