### ISSUE TITLE
OSM Importer load warning

### ISSUE THREAD

**Issue by gitToad** [sideeffects/GameDevelopmentToolset#53]
Houdini 16.5
Game Dev Toolset 16.5 branch

_Warning: "/obj/geo1/sop_osm_importer1" using incomplete asset definition (full definition not found).
The following node types are using incomplete asset definitions:
Sop/sop_osm_importer_

Node info on the OSM importer sop says:

_This node is using an incomplete asset definition. 
It will not function properly until the asset library containing the full definition is installed._

also noticed the sop is missing its OSM icon.

**Comment by lkruel** [comment]
Hey there, I believe this is caused by the 16.5 branch having some names renamed. Specifically adding the gamedev namespace. Are you able to drop in a new OSM Import node to replace in your existing files?

**Comment by gitToad** [comment]
Yep, with newly instantiated OSM import node this issue no longer occurs - thanks for the tip !
