### ISSUE TITLE
OSM importer: hou_id not 64 bit int ?

### ISSUE THREAD

**Issue by gitToad** [sideeffects/GameDevelopmentToolset#54]
Per OSM docs http://wiki.openstreetmap.org/wiki/Elements#Common_attributes
the node or way IDs are **64 bit integers**.

I have noticed that after import some hou_id's are negative (and do not correspond to any OSM ids in the OSM file) - I suspect this is due to overflow ? Perhaps hou_id is being read/processed or stored as a 32bit int somewhere ?

For example OSM id (in the file) 2402018120 (a house on 122 Tennyson Ave in Palo Alto)
becomes hou_id -1892949176

I hope Houdini integer attributes can be 64 bits or else that hou_id might have to turn into a string type ?

**Comment by lkruel** [comment]
Thanks for letting me know. I've updated the 16.5 branch with the ids being strings and not ints
