### ISSUE TITLE
rop_games_baker

### ISSUE THREAD

**Issue by Limbicnation** [sideeffects/GameDevelopmentToolset#57]
Hi I'm getting an error in the 'rop_games_baker' node when I hit render. here is the issue: `
Error 
Error rendering child: /out/rop_games_baker1/baketexture 
Error 
Error rendering child: /out/rop_games_baker1/pre_bake0 
Warning 
Skipping unrecognized parameter "pr". 
Warning 
Skipping unrecognized parameter "sssmodel". 
Warning 
Skipping unrecognized parameter "sssphase". 
Warning 
Skipping unrecognized parameter "opacpackedalpha". 
Warning 
Skipping unrecognized parameter "roundedEdge_enable". 
Warning 
Skipping unrecognized parameter "roundedEdge_radius". 
Warning 
Skipping unrecognized parameter "roundedEdge_mode". 
Warning 
Skipping unrecognized parameter "pr". 
Warning 
Skipping unrecognized parameter "pr". 
Warning 
Skipping unrecognized parameter "pr". 
Warning 
Skipping unrecognized parameter "pr". 
Warning 
Skipping unrecognized parameter "parmgroup_pivotxform". 
Warning 
Skipping unrecognized parameter "pr". 
Warning 
Skipping unrecognized parameter "parmgroup_prexform". 
Warning 
Skipping unrecognized parameter "prexform_xOrd". 
Warning 
Skipping unrecognized parameter "prexform_rOrd". 
Warning 
Skipping unrecognized parameter "prexform_t". 
Warning 
Skipping unrecognized parameter "prexform_r". 
Warning 
Skipping unrecognized parameter "prexform_s". 
Warning 
Skipping unrecognized parameter "prexform_shear". 
Message 
[/out/rop_games_baker1/objnet]

Message 
[/out/rop_games_baker1/objnet/matnet/plain_white]

Message 
[/out/rop_games_baker1/objnet/custom_export]

Message 
[/out/rop_games_baker1/objnet/low]

Message 
[/out/rop_games_baker1/objnet/high]

Message 
[/out/rop_games_baker1/objnet/cam1]

Message 
[/out/rop_games_baker1/objnet/cam1/xform1]

`

**Comment by lkruel** [comment]
Hey there! 

What version of Houdini are you using? The latest tools require 16.5

**Comment by Limbicnation** [comment]
Hi Luiz. I'm still on 16.0.736. That's the issue. Thank you.
