### ISSUE TITLE
Simple baker - Custom channel Error :

### ISSUE THREAD

**Issue by PascalBkm** [sideeffects/GameDevelopmentToolset#59]
Hello the team,

here are 2 issues with the simple baker :

1) Custom channel baking give me this error :

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "opdef:/Sop/sop_simple_baker?PythonModule", line 4, in render
  File "C:/PROGRA~1/SIDEEF~1/HOUDIN~1.268/houdini/python2.7libs\houpythonportion.py", line 3136, in decorator
    return func(*args, **kwargs)
  File "C:/PROGRA~1/SIDEEF~1/HOUDIN~1.268/houdini/python2.7libs\hou.py", line 42467, in render
    return _hou.RopNode_render(*args, **kwargs)
OperationFailed: The attempted operation failed.

Attach : .hip test file.
[Setup_HIP.zip](https://github.com/sideeffects/GameDevelopmentToolset/files/1578033/Setup_HIP.zip)

2) I'm trying a workaround, by storing my @v in @Cd, so I can use the vertex color baking. but for some reason, every negative component of my @v vector returns a 0 value once the image baked. We should be able to write negative value in a .exr format right ?

Have a good day.

**Comment by PascalBkm** [comment]
Hello,

Actually that's probably a more general issue I have with Houdini, is it possible to export signed .exr ?

**Comment by rpopovici** [comment]
I get a similar error. the solution was to reduce the size of the bake to 512x512 :(
Check this thread https://www.sidefx.com/forum/topic/51867/?page=1#post-233595

Btw, I use Houdini apprentice. maybe that's why..

**Comment by Ambrosiussen** [comment]
@PascalBkm You should be able to do that already. I tried both the .exr with negative values & custom attributes such as @v. 
I am closing this issue, but feel free to reopen if you can reproduce this problem. :)
