### ISSUE TITLE
sop_autouv crashes houdini

### ISSUE THREAD

**Issue by doppioslash** [sideeffects/GameDevelopmentToolset#60]
Windows 10. with the lastest updates as of 5 Jan 2018
Houdini Indie 16.5.323
GameDevelopmentToolset 1.8, stable, installed with the "Update Toolset" tool.

When pressing 5 on the viewport on this [Houdini Project file](https://www.dropbox.com/s/z4yuh77is4u5eiy/test02Uvs.hiplc?dl=0), with the sop_autouv node set to display, Houdini will crash 100% of the time.

[Here is the log](https://github.com/sideeffects/GameDevelopmentToolset/files/1607439/crash.test02Uvs.claud_78608_log.txt):
```
Crash report from claud; Houdini Version 16.5.323 [Windows 10.0.10586]
Uptime 352 seconds
Fri Jan  5 17:53:08 2018
Caught signal 11

Traceback from 78608 ThreadId=0x0000dd70
CURRENT THREAD 56688
+0x69834efe [GUI_GeoRender::buildEdgeHighlight]
+0x6984c7ba [GUI_GeoRender::update]
+0x69826303 [GUI_DetailLook::updateForRender]
+0x69585582 [DM_VPortAgent::setupGeometry]
+0x695826cb [DM_VPortAgent::renderViewport]
+0x69572ddb [DM_VPortAgent::doRender]
+0x6955177a [DM_Viewport::doRender]
+0x68e9db0c [UI_Feel::renderMe]
+0x68e98f16 [UI_Feel::doRenderKids]
+0x68e98df4 [UI_Feel::doRender]
+0x68e9db0c [UI_Feel::renderMe]
+0x68e98f16 [UI_Feel::doRenderKids]
+0x68e98df4 [UI_Feel::doRender]
+0x68f83120 [UI_Viewport::reRender]
+0x68f88ff1 [UI_Window::renderChildViews]
+0x68f8634d [UI_Window::doRedrawSubclass]
+0x6954981f [DM_ViewLayout::doMakeTriple]
+0x68f88a08 [UI_Window::redrawRequest]
+0x68f2e1fa [UI_Queue::doWindowRedraws]
+0x68f2e348 [UI_Queue::drain]
+0x68f2e83c [UI_Queue::eventLoop]
+0x69e424d0 [AP_Interface::loadWindowGeometry]
+0x69e42ca9 [myWinMain]
+0x0a8d16cb
+0x983f1fe4 [BaseThreadInitThunk]
+0x98b4ef91 [RtlUserThreadStart]
```

**Comment by Ambrosiussen** [comment]
Hi,

Could you try using the 1.9 Development version of the Toolset? The stable version is missing several fixes which have already been published in Development. (Newest)

Paul

**Comment by benhenry96** [comment]
Mine also seems to be crashing. It doesn't seem to handle higher res geometry (30k) because I tried it on a small sphere and it worked beautifully.

**Comment by lkruel** [comment]
Couldn't repro this on the latest.
