### ISSUE TITLE
No fracture animation export

### ISSUE THREAD

**Issue by Milchbroetchenpruegler** [sideeffects/GameDevelopmentToolset#61]
I downloaded the gamedev toolset and i got most of the tools but the fracture animation export is missing

https://imgur.com/lGrDl4t

Pls help

**Comment by Ambrosiussen** [comment]
Hi,

The shelf only shows some of the tools (Due to the limited amount of screenspace).
If you tab / rightclick in your network view and type "GameDev", you will see all GameDev tools functioning in that context. Just like any other node would.

Paul
