### ISSUE TITLE
ROP_games_baker

### ISSUE THREAD

**Issue by TheBenOfficial** [sideeffects/GameDevelopmentToolset#65]
I am getting the error, "error rendering child". 

Im running 16.5.323

This is a 300 frame bake out from a high-poly fluid surface to its low-poly counterpart. Both are already cached to objs. I am rendering basecolor and normal maps. What's strange is that everything worked fine up till the 107th frame. It renders a black base color and a blank purple normal map, then it tries to move on to the 108th frame but I don't see it creating the temp file first, (like it had been doing). It just hangs.

It was working so beautifully then it just stopped at frame 107.

I guess I'll get the new .378 production build and see what happens.

**Comment by TheBenOfficial** [comment]
I forgot...
This is Houdini Indie Limited Commercial:


ROP_games_baker:

"Error 
Error rendering child: /out/rop_games_baker1/pre_bake0 "



pre_bake0:
```
Error 
Python error: Traceback (most recent call last):
File "", line 1, in 
File "opdef:/Driver/rop_games_baker?PythonModule", line 58, in pre_bake
File "C:/PROGRA~1/SIDEEF~1/HOUDIN~1.378/houdini/python2.7libs\houpythonportion.py", line 1071, in set
self._set(value)
File "C:/PROGRA~1/SIDEEF~1/HOUDIN~1.378/houdini/python2.7libs\hou.py", line 40042, in _set
def _set(*args): return _hou.Parm__set(*args)
KeyboardInterrupt"
```

**Comment by Ambrosiussen** [comment]
Hi,

Could you try updating the Toolset? (To Development 1.9)

Thanks,
Paul

**Comment by artsak666** [comment]
hi
I want to use beker with an external renderer (redshift). I think that there is a need, but is there a way to deal with it?

If there is RS correspondence it would be nice if there is an option to display bake images.

**Comment by Ambrosiussen** [comment]
Implementing additional baking solutions is part of our roadmap.
(Marmoset Toolbag, xNormal amongst others)
Closing this issue.
