### ISSUE TITLE
Remove scripts/123.py

### ISSUE THREAD

**Issue by ghost** [sideeffects/GameDevelopmentToolset#66]
Hello,

The 123.py appears to do nothing functional, but comes with the liability that it might be executed before your studio/other 123 and thereby prevent further execution.

Could we just have it removed from the repo?

Regards,
Jason

**Comment by lkruel** [comment]
Hey Jason, 

That file is already gone in the development branch. We'll be pushing a 1.10 version in the next couple of days and that should also make it into Stable. 

Luiz

**Comment by ghost** [comment]
Ah great - thanks!
