### ISSUE TITLE
sop_edgegroup_to_curve.hda selected color is not used

### ISSUE THREAD

**Issue by brunokindt** [sideeffects/GameDevelopmentToolset#69]
Selecting a color in the sop_edgegroup_to_curve doesn't update the displayed wire color. 
`polywire_color` is not used by the Color Sop inside the hda.

GameDevelopmentToolset Development branch
houdini version 16.5.405

**Comment by lkruel** [comment]
Thanks for the report! This will be fixed in tomorrow's daily GameDev build 

https://github.com/sideeffects/GameDevelopmentToolset/commit/b8e65f076e85cbef450b2576b24c7b4961fc3770
