### ISSUE TITLE
Should this GameDevelopmentToolset work in Apprentice?

### ISSUE THREAD

**Issue by ocalaf** [sideeffects/GameDevelopmentToolset#7]
Maybe I'm doing something wrong during the installation or maybe it just will not work in apprentice, but I couldn't find these "beta" ROPs under MacOS

**Comment by ocalaf** [comment]
it works in Indie under Windows 10

**Comment by mikelyndon-sesi** [comment]
Because you can't export geometry with apprentice the HDA will fail.  Also, in apprentice the renders are watermarked which would effect the vertex animation textures.

**Comment by ocalaf** [comment]
That makes totally sense, fortunately I've been able to test it a bit since
I got an Indie license thank's to the GlobalGameJam!

thanks for your answers!

2017-05-16 20:23 GMT+02:00 Mike Lyndon <notifications@github.com>:
