### ISSUE TITLE
RBD to FBX scaling issues

### ISSUE THREAD

**Issue by Limbicnation** [sideeffects/GameDevelopmentToolset#70]
To not get any wired scaling issues with RBD fractured objects, I noticed to set the following expression for START and END frame in the RBD to FBX Settings. - https://imgur.com/a/xA3G0

**Comment by Limbicnation** [comment]
I’m still having the issue that it would set a smaller scale for the first frame.

**Comment by Ambrosiussen** [comment]
Hi,
I have not been able to reproduce the problem you are having. 
We did recently implement per piece scaling in the logic, which is what might have fixed it.
I am closing this issue, but feel free to re-open if you can reproduce it.
