### ISSUE TITLE
Simple Baker's Position output

### ISSUE THREAD

**Issue by patrickjreece** [sideeffects/GameDevelopmentToolset#74]
I can't get the P output to work, any ideas?

**Comment by lkruel** [comment]
Do you have any more information on this issue? Perhaps a sample scene of what you're trying to do?

**Comment by Ambrosiussen** [comment]
Hi, thanks for reporting.
I have confirmed that the P output of the games baker & simple baker would return a grey image.
This has been fixed, and has been submitted. It will be part of release 1.24 and newer.
