### ISSUE TITLE
sop_edgegroup_to_curve.hda group dropdown menu does not pick up defined group

### ISSUE THREAD

**Issue by pilot3d** [sideeffects/GameDevelopmentToolset#77]
sop_edgegroup_to_curve.hda **Group** dropdown menu does not pick up defined group - it doesn't show as selection choice, however when group name is typed manually into field node works correctly

**Comment by lkruel** [comment]
Fixed! Thanks for reporting. 

Fix will be in tomorrow's daily build

https://github.com/sideeffects/GameDevelopmentToolset/commit/8f5da8d87cbc76b98d124905f371262dcca7efc1
