### ISSUE TITLE
GameDev Octahedron Lens not packaged

### ISSUE THREAD

**Issue by Rayfoundry** [sideeffects/GameDevelopmentToolset#78]
Cloning fresh GameDev tools from Development branch gives:

`"/obj/obj_impostor_camera_rig1/shopnet1/shop_octahedron_impostor_lens1" using incomplete asset definition (full definition not found). `

in the impostor camera rig. The turntable shader hda is referenced correctly and source controlled. The newer octahedral lens cvex lens shader is not source controlled and marked as embedded (but has a incomplete asset definition?)

**Comment by Ambrosiussen** [comment]
Thanks for reporting. HDA has been submitted!
