### ISSUE TITLE
Vertex Animation Textures / BBOX MIN / MAX values not populated on render

### ISSUE THREAD

**Issue by michela** [sideeffects/GameDevelopmentToolset#8]
Following the GDC video when I render the Vertex Animation Textures HDA the BBOX min / max values are never populated. I've attached a project reflecting what's in the video. Is there a missing step? Tested with HOU16.0.557 and 16.0.600

[cloth.zip](https://github.com/sideeffects/GameDevelopmentToolset/files/998245/cloth.zip)

**Comment by mikelyndon-sesi** [comment]
This has been fixed in the development branch.  Please download and try that version.
