### ISSUE TITLE
merge-small-islands and uvflatten error

### ISSUE THREAD

**Issue by carstenkolve** [sideeffects/GameDevelopmentToolset#83]
hou 16.5.268 on osx, gamedev toolset 1.43

when creating a merge small islands sop, i get these errors - however creating the uvflatten node on its own is no problem

Warning:     Skipping unrecognized parameter "uvattrib".
        [/obj/geo1/sop_merge_small_islands1/connectivity6]

Warning:     Skipping unrecognized parameter "uvattrib".
        [/obj/geo1/sop_merge_small_islands1/connectivity7]

Error:       Bad node type found: uvflatten::2.0 in /obj/geo1/sop_merge_small_islands1.
Warning:     Unknown channel(s) "method, uvattrib" converted to spare parameter(s).
        [/obj/geo1/sop_merge_small_islands1/uvflatten7]

,,,,

**Comment by Ambrosiussen** [comment]
Hi,

This is caused by some of the nodes inside the tool being from a newer version of Houdini.
Please update your Houdini version to get rid of these problems. :)

Paul
