### ISSUE TITLE
How to use the demo mesh tiler mesh_tiler_demoscene.hip? 

### ISSUE THREAD

**Issue by wavebit** [sideeffects/GameDevelopmentToolset#85]
Hello
I just add a color node with a random color. The baker result is not like the tutorial shows.
![cap1](https://user-images.githubusercontent.com/11334491/46746909-9e946280-cce2-11e8-8f4a-85a3c9d94fcc.png)
![cap2](https://user-images.githubusercontent.com/11334491/46746915-a3591680-cce2-11e8-9b61-30295a4a9cb6.png)

Environment:
Windows 10
Houdini 16.5.571
GameDevelopmentToolset-1.60

**Comment by Ambrosiussen** [comment]
Hi, this has been fixed. It was caused by something that broke in the baking tool.
Please update to the latest version (scene file too), and try again! :)

Paul
