### ISSUE TITLE
‘hedgegroup’ is not a valid group in DetailMesh

### ISSUE THREAD

**Issue by morriekken** [sideeffects/GameDevelopmentToolset#88]
I am trying to get to work DetailMesh from Game Dev tools - but I struggle to get any result out of it. I have seen tutorial and tried to feed it with either houdini simple geometry or have created some simple geometry in blender then fed it as abc file into houdini. Same result in all cases.

This is what I am doing:
I have created box as a template geometry, UV'ed it and have some details in abc file loaded with File node. 
Then I got:

Error 
Invalid source /obj/box_object1/sop_detail_mesh1/polyfill1
Error: ‘hedgegroup’ is not a valid group..

Am I doing something wrong?
Be mindful I am using Houdini for 1 week.

Version: Houdini 16.5.571 Apprentice and Game Dev tools 1.43

**Comment by morriekken** [comment]
The same issue appears with Houdini Apprentice 17.0.352 and Game Dev Tools 1.6.
[DetailMeshTest.zip](https://github.com/sideeffects/GameDevelopmentToolset/files/2497400/DetailMeshTest.zip)

**Comment by Ambrosiussen** [comment]
Hi,

I looked at your file. It seems that the mesh you are projecting (right input) is a packed alembic.. The tool only works with polygons. What you could do is drop down a convert node under your file sop, which will make it work perfectly. I modified the tool to do this for you now. It will be part of release 1.70 and newer.

As for your file, I recommend setting your tile depth scalar to a negative values to prevent an inverted mesh.

Paul
