### ISSUE TITLE
UE4 editor will crash when switching Asset Input selection frequently

### ISSUE THREAD

**Issue by wavebit** [sideeffects/GameDevelopmentToolset#89]
Hi,
Original post is here
https://www.sidefx.com/forum/topic/58507/#post-262319

This is the crash report generated by UE4.
[Crash-MyProject33.zip](https://github.com/sideeffects/GameDevelopmentToolset/files/2498714/Crash-MyProject33.zip)

System:
Windows 10
UE4.20.3
Houdini Engine 16.5.623

**Comment by lkruel** [comment]
Thanks, but this isn't the place for these type of requests. Feel free to also send this to support@sidefx.com if you haven't done it yet
