### ISSUE TITLE
GoZ: Side Primitives are not exported after Extrude

### ISSUE THREAD

**Issue by mifth** [sideeffects/GameDevelopmentToolset#91]
Hi. 
I found an issue.
1.70 GDTools
H17

https://youtu.be/by0rFiCVqWQ

![temp_1](https://user-images.githubusercontent.com/2251298/48842835-65054b80-eda6-11e8-95eb-575ab1bc323b.png)
![temp_2](https://user-images.githubusercontent.com/2251298/48842841-69c9ff80-eda6-11e8-9fa4-72618d0f0ef7.png)

**Comment by mifth** [comment]
To repeat:
- Export to zbrush a mesh
- Import from ZB a mesh
- Select some Polygons and make Extrude
- Export to ZB again.

Side polygons of the extrude will not be exported.

**Comment by mifth** [comment]
Hello,
  I did a modification of the GameDev GoZ. I simplified code and moved the GoZ at Object level.
Now it's possible to change every subtool separetely and make any modification. It's really fast for modeling/sculpting. 
  I also removed the server. Instead of the server you should press Import button.
  I hope you can add it to GDTools too. 

Here is a test:
https://www.youtube.com/watch?v=15zikh-wjAM

- GoZ is moved to Object level for better meshes modifications.
- Server is removed and code is simplified.
- ZB Folders are moved to Settings tab so that Mac users could change their paths.

The asset is here: https://github.com/mifth/mifthtools/raw/master/houdini/otls/other/mifth_simple_goz.otllc

**Comment by lkruel** [comment]
Cool! 

Was there a reason for disabling the server? Seems like you'd want to just hit export on Zbrush and not have to deal with it on the Houdini side. 

I'll take a look at it to see how to best integrate some of the changes, the workflow is pretty different so I'll have to think some about how to have possibly both workflows supported. 

Currently subtools come in as the name attribute, that way if you have an object with hundreds of subtools you don't need to merge them all in to see the full object, but you can still easily isolate the subtools and manage them individually

**Comment by mifth** [comment]
The server was used only for one reason. Auto-press the Import button. This is a really unneeded thing. 
I prefer to control manually such things.
You can add the server, but please, make a checkbox to disable it. For me I don't see a point to use the server. )

About Obj/Sop. Yes I know about the name Attribute. But it's not a comfort way for scupltors/modellers. It looks like a mess of meshes for me. ) I cannot even make an extrude or just merge some other meshes. It's not so comfortable for me.
Also, as far as I know Maya and Max plugins separate the subtools to objects. 

Thank you. I hope it will be at the GDTools. )

**Comment by lkruel** [comment]
Valid points, I think there are 2 workflows, one where you're sending individual subtools back and forth to polish and sculpt as your working, and the other one is to use it to process data, like sending things to Zbrush for ZRemesh or sending them to Houdini to decimate and bake. 

I'll think a little bit about what version 2.0 of the plugin will look like and ping you to see if it fits your needs. I've also thought about using the GoZ plugin for shot sculpting, where you can modify a frame of an animation and bring it back in place, so the new workflows will have to consider that as well

**Comment by mifth** [comment]
I have an idea. We can add 2 modes.

First mode will separete subtools at objects.
Second mode will merge all subtools into one object. There will be only one object with all subtools.

Something like this:
![image](https://user-images.githubusercontent.com/2251298/48854538-35187100-edc3-11e8-8c21-bb2c6af1c82b.png)

Or you can use Name Attribute as you like.
I can make a prototype if you want.
