### ISSUE TITLE
Feature Request: Export to usdz format for Apple AR/VR

### ISSUE THREAD

**Issue by vasilistriantafyllou** [sideeffects/GameDevelopmentToolset#95]
Creating Content for Apple ARKit - https://developer.apple.com/arkit/gallery/

**Comment by Ambrosiussen** [comment]
Hi,

For general RFE's not specific to the GameDevToolset I would like to ask you to request them here:
https://www.sidefx.com/bugs/submit/

Thanks,
Paul
