### ISSUE TITLE
Flow map visualize direction error in preview

### ISSUE THREAD

**Issue by Jiucao** [sideeffects/GameDevelopmentToolset#97]
Although the flowmap has connected to the guide node, the vector direction in the viewport still not changed
And how to bake and export the flowmap, then use it in game engines
The flowmap always could not read cd attribute from previous node when select color mode

**Comment by Ambrosiussen** [comment]
Hi,

I recommend watching the following videos.

Using the visualize node:
https://vimeo.com/292711968

Taking it to engine (Including baking):
https://vimeo.com/243733565

Paul
